Readme rust update
security-union/armore-server pull request #22
Opened 2021-01-31 14:15 UTC by JasterV

I've changed the steps necessary to test and run the rust server

2021-01-31 18:36 UTC, darioalessandro submitted a review, later dismissed

2021-02-01 20:48 UTC, griffobeid requested changes
You're gonna have to rebase this branch with dev because I moved the location of the helm chart :/

2021-02-01 20:56 UTC, griffobeid commented
@JasterV It might be easiest to just create a new branch in this case

2021-02-07 22:41 UTC, JasterV commented
Moved to #30

2021-02-07 22:41 UTC, closed without merging