[Arm-193] Open source Contributing guide & Code of conduct
security-union/armore-server pull request #30
Opened 2021-02-07 22:40 UTC by JasterV

Stills in progress

2021-02-12 03:08 UTC, griffobeid requested changes
Just a few minor things, this looks awesome otherwise 👏 💯

2021-02-12 03:08 UTC, griffobeid commented on CONTRIBUTING.md
> +Feel free to contribute regardless of your age, gender, race or any other discriminating factor (Check out [code of conduct](./CODE_OF_CONDUCT.md) for more) and contact us on [discord](https://discor
```suggestion
Feel free to contribute regardless of your age, gender, race or any other discriminating factor (Check out [code of conduct](./CODE_OF_CONDUCT.md) for more) and contact us on [discord](https://discord.gg/mptG9ZGxTF) if you have any questions, we are glad to have you here!
```

2021-02-12 03:08 UTC, griffobeid commented on CONTRIBUTING.md
> +Armore is divided into 4 main repositories: _Android_, _iOs_, _Server_ & _Web_.
```suggestion
Armore is divided into 4 main repositories: _Android_, _iOS_, _Server_ & _Web_.
```

2021-02-12 03:08 UTC, griffobeid commented on CONTRIBUTING.md
> +For now we are mainly open sourcing the Server repo to the community. If you are interested in collaborating with the android, iOs or Web code (which we will open soon) contact us!
```suggestion
For now we are mainly open sourcing the Server repo to the community. If you are interested in collaborating with the android, iOS or Web code (which we will open soon) contact us!
```

2021-02-14 00:43 UTC, darioalessandro approved these changes
lgtm!

2021-02-14 21:50 UTC, griffobeid approved these changes

2021-02-14 21:55 UTC, merged